export const skillsData = [
  { name: "JavaScript", logo: "/icons/js.svg" },
  { name: "TypeScript", logo: "/icons/ts.svg" },
  { name: "ReactJs", logo: "/icons/react.svg" },
  { name: "Node.js", logo: "/icons/node.svg" },
  { name: "NextJs", logo: "/icons/next.svg" },
  { name: "Redux", logo: "/icons/redux.svg" },
  { name: "MobX", logo: "/icons/mobx.svg" },
  { name: "MongoDB", logo: "/icons/mongo.svg" },
  { name: "ExpressJs", logo: "/icons/express.svg" },
  { name: "Mongoose", logo: "/icons/mongo.svg" },
  { name: "Tailwind", logo: "/icons/tailwind.svg" },
  { name: "Bootstrap", logo: "/icons/bootstrap.svg" },
  { name: "Knex", logo: "/icons/knex.svg" },
  { name: "Sequelize", logo: "/icons/sequelize.svg" },
  { name: "Sass/Less", logo: "/icons/sass.svg" },
  { name: "HTML", logo: "/icons/html.svg" },
  { name: "CSS", logo: "/icons/css.svg" },
  { name: "Webpack", logo: "/icons/webpack.svg" },
  { name: "Vite", logo: "/icons/vite.svg" },
  { name: "Git", logo: "/icons/git.svg" },
  { name: "Pug", logo: "/icons/pug.svg" },
  { name: "C++", logo: "/icons/cpp.svg" },
];
